import { Doctor, Appointment, Clinic } from '../types';

export const doctors: Doctor[] = [
  {
    id: '1',
    name: 'Dr. Sarah Wilson',
    email: 'dhivyaam.it2023@citchennai.net',
    password: 'dhivyaa123',
    specialty: 'Cardiology', // Chest Pain
    experience: 15,
    degrees: ['MD Cardiology', 'Fellowship in Interventional Cardiology'],
    achievements: ['Best Cardiologist Award 2023', 'Published 50+ Research Papers'],
    rating: 4.9,
    reviews: 245,
    image: 'https://images.pexels.com/photos/5215024/pexels-photo-5215024.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  },
  {
    id: '2',
    name: 'Dr. Michael Chen',
    email: 'kamalis2509@gmail.com',
    password: 'kamali123',
    specialty: 'Dermatology', // Skin Rash
    experience: 12,
    degrees: ['MD Dermatology', 'Board Certified Dermatologist'],
    achievements: ['Excellence in Skin Care Award', 'Top 10 Dermatologists 2023'],
    rating: 4.8,
    reviews: 189,
    image: 'https://images.pexels.com/photos/6129967/pexels-photo-6129967.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  },
  {
    id: '3',
    name: 'Dr. Anil Mehra',
    email: 'anil.mehra@hospital.com',
    password: 'anil123',
    specialty: 'Orthopedics', // Joint Pain
    experience: 18,
    degrees: ['MS Orthopedics', 'Fellowship in Joint Replacement'],
    achievements: ['Top Orthopedic Surgeon 2022'],
    rating: 4.6,
    reviews: 410,
    image: 'https://images.pexels.com/photos/6749777/pexels-photo-6749777.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  },
  {
    id: '4',
    name: 'Dr. Vikram Joshi',
    email: 'vikram.joshi@hospital.com',
    password: 'vikram123',
    specialty: 'General Medicine', // Fever
    experience: 9,
    degrees: ['MD General Medicine'],
    achievements: ['National Immunization Champion'],
    rating: 4.6,
    reviews: 190,
    image: 'https://images.pexels.com/photos/8376266/pexels-photo-8376266.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  },
  {
    id: '5',
    name: 'Dr. Emily Davis',
    email: 'emily.davis@hospital.com',
    password: 'emily123',
    specialty: 'Neurology', // Headache
    experience: 10,
    degrees: ['MD Neurology'],
    achievements: ['Neuroscience Research Award'],
    rating: 4.5,
    reviews: 312,
    image: 'https://images.pexels.com/photos/8460150/pexels-photo-8460150.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  },
  {
    id: '6',
    name: 'Dr. Priya Sharma',
    email: 'priya.sharma@hospital.com',
    password: 'priya123',
    specialty: 'Gastroenterology', // Stomach Pain
    experience: 14,
    degrees: ['MD Gastroenterology'],
    achievements: ['Digestive Health Award'],
    rating: 4.7,
    reviews: 233,
    image: 'https://images.pexels.com/photos/8460167/pexels-photo-8460167.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  },
  {
    id: '7',
    name: 'Dr. Rajeev Nair',
    email: 'rajeev.nair@hospital.com',
    password: 'rajeev123',
    specialty: 'Spine & Pain Specialist', // Back Pain
    experience: 13,
    degrees: ['MS Orthopedics', 'Fellowship in Spine Care'],
    achievements: ['Best Spine Specialist Award'],
    rating: 4.4,
    reviews: 150,
    image: 'https://images.pexels.com/photos/8460068/pexels-photo-8460068.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  },
  {
    id: '8',
    name: 'Dr. Aisha Khan',
    email: 'aisha.khan@hospital.com',
    password: 'aisha123',
    specialty: 'Allergy & Immunology', // Allergies
    experience: 11,
    degrees: ['MD Allergy & Immunology'],
    achievements: ['Allergy Specialist of the Year'],
    rating: 4.8,
    reviews: 275,
    image: 'https://images.pexels.com/photos/7749090/pexels-photo-7749090.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  },
  {
    id: '9',
    name: 'Dr. Kevin Patel',
    email: 'kevin.patel@hospital.com',
    password: 'kevin123',
    specialty: 'Endocrinology', // Diabetes
    experience: 14,
    degrees: ['MD Endocrinology'],
    achievements: ['Diabetes Control Excellence Award'],
    rating: 4.6,
    reviews: 225,
    image: 'https://images.pexels.com/photos/6749778/pexels-photo-6749778.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  },
  {
    id: '10',
    name: 'Dr. James Thompson',
    email: 'james.thompson@hospital.com',
    password: 'james123',
    specialty: 'Pediatrics', 
    experience: 20,
    degrees: ['MD Pediatrics Medicine', 'Board Certified'],
    achievements: ['Community Service Award', '25 Years of Excellence'],
    rating: 4.7,
    reviews: 567,
    image: 'https://images.pexels.com/photos/5215024/pexels-photo-5215024.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  },
  {
    id: '11',
    name: 'Dr. Renu Gupta',
    email: 'renu.gupta@hospital.com',
    password: 'renu123',
    specialty: 'Cardiology',
    experience: 17,
    degrees: ['MD Cardiology', 'PhD in Cardiovascular Sciences'],
    achievements: ['Heart Health Research Award'],
    rating: 4.8,
    reviews: 198,
    image: 'https://images.pexels.com/photos/8460064/pexels-photo-8460064.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  },
  {
    id: '12',
    name: 'Dr. Rakesh Verma',
    email: 'rakesh.verma@hospital.com',
    password: 'rakesh123',
    specialty: 'Dermatology',
    experience: 10,
    degrees: ['MD Dermatology'],
    achievements: ['National Skin Expert Award'],
    rating: 4.6,
    reviews: 164,
    image: 'https://images.pexels.com/photos/8460176/pexels-photo-8460176.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  },
  {
    id: '13',
    name: 'Dr. Sunita Rao',
    email: 'sunita.rao@hospital.com',
    password: 'sunita123',
    specialty: 'Orthopedics',
    experience: 16,
    degrees: ['MS Orthopedics', 'Diploma in Sports Medicine'],
    achievements: ['Women in Orthopedics Excellence Award'],
    rating: 4.5,
    reviews: 201,
    image: 'https://images.pexels.com/photos/8460165/pexels-photo-8460165.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  },
  {
    id: '14',
    name: 'Dr. Harish Menon',
    email: 'harish.menon@hospital.com',
    password: 'harish123',
    specialty: 'General Medicine',
    experience: 8,
    degrees: ['MD General Medicine'],
    achievements: ['Top General Practitioner 2023'],
    rating: 4.3,
    reviews: 160,
    image: 'https://images.pexels.com/photos/6749775/pexels-photo-6749775.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  },
  {
    id: '15',
    name: 'Dr. Neha Roy',
    email: 'neha.roy@hospital.com',
    password: 'neha123',
    specialty: 'Neurology',
    experience: 13,
    degrees: ['MD Neurology', 'Fellowship in Epilepsy'],
    achievements: ['Brain Health Innovation Award'],
    rating: 4.7,
    reviews: 249,
    image: 'https://images.pexels.com/photos/8460153/pexels-photo-8460153.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  },
  {
    id: '16',
    name: 'Dr. Farhan Ali',
    email: 'farhan.ali@hospital.com',
    password: 'farhan123',
    specialty: 'Gastroenterology',
    experience: 11,
    degrees: ['MD Gastroenterology'],
    achievements: ['Liver & Gut Research Grant Winner'],
    rating: 4.6,
    reviews: 188,
    image: 'https://images.pexels.com/photos/8460168/pexels-photo-8460168.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  },
  {
    id: '17',
    name: 'Dr. Kavitha Iyer',
    email: 'kavitha.iyer@hospital.com',
    password: 'kavitha123',
    specialty: 'Spine & Pain Specialist',
    experience: 15,
    degrees: ['MS Orthopedics', 'Pain Management Fellowship'],
    achievements: ['Best Spine Therapist Award 2022'],
    rating: 4.5,
    reviews: 172,
    image: 'https://images.pexels.com/photos/8460175/pexels-photo-8460175.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  },
  {
    id: '18',
    name: 'Dr. Imran Qureshi',
    email: 'imran.qureshi@hospital.com',
    password: 'imran123',
    specialty: 'Allergy & Immunology',
    experience: 10,
    degrees: ['MD Immunology'],
    achievements: ['National Immunotherapy Award'],
    rating: 4.7,
    reviews: 220,
    image: 'https://images.pexels.com/photos/8460151/pexels-photo-8460151.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  },
  {
    id: '19',
    name: 'Dr. Sneha Kapoor',
    email: 'sneha.kapoor@hospital.com',
    password: 'sneha123',
    specialty: 'Endocrinology',
    experience: 12,
    degrees: ['MD Endocrinology'],
    achievements: ['Young Diabetes Researcher Award'],
    rating: 4.6,
    reviews: 209,
    image: 'https://images.pexels.com/photos/8460174/pexels-photo-8460174.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  },
  {
    id: '20',
    name: 'Dr. Abhinav Desai',
    email: 'abhinav.desai@hospital.com',
    password: 'abhinav123',
    specialty: 'Pediatrics',
    experience: 18,
    degrees: ['MD Pediatrics'],
    achievements: ['Best Pediatrics Clinician 2022'],
    rating: 4.8,
    reviews: 298,
    image: 'https://images.pexels.com/photos/6749776/pexels-photo-6749776.jpeg?auto=compress&cs=tinysrgb&w=400',
    available: true,
  }


];

export const appointments: Appointment[] = [
  {
    id: '1',
    patientName: 'John Smith',
    age: 45,
    phone: '(555) 123-4567',
    email: 'john.smith@email.com',
    address: '123 Main St, City, State',
    disease: 'Chest Pain',
    preferredDoctor: 'Dr. Sarah Wilson',
    timeSlot: '09:00 AM',
    date: '2024-01-15',
    status: 'confirmed',
  },
  {
    id: '2',
    patientName: 'Mary Johnson',
    age: 32,
    phone: '(555) 987-6543',
    email: 'mary.johnson@email.com',
    address: '456 Oak Ave, City, State',
    disease: 'Skin Rash',
    preferredDoctor: 'Dr. Michael Chen',
    timeSlot: '10:30 AM',
    date: '2024-01-16',
    status: 'pending',
  },
  {
    id: '3',
    patientName: 'Alice Brown',
    age: 29,
    phone: '(555) 246-1357',
    email: 'alice.brown@email.com',
    address: '789 Pine Rd, City, State',
    disease: 'Fever',
    preferredDoctor: 'Dr. Vikram Joshi',
    timeSlot: '11:00 AM',
    date: '2024-01-17',
    status: 'confirmed',
  }
];

export const allowedDoctors = doctors.map(({ email, password, name, id }) => ({
  email,
  password,
  name,
  doctorId: id,
}));

export const clinic: Clinic = {
  name: 'MediCare Plus Hospital',
  ranking: 'Top 5 Hospital in South India',
  awards: [
    'Best Multi-speciality Hospital 2022',
    'Excellence in Patient Care Award',
    'National Health Accreditation',
    'Top Infrastructure Recognition',
  ],
  totalPatients: 56000,
  totalDoctors: 120,
  rating: 4.8,
  reviews: 1224,
};

export const specialties = [
  { name: 'Cardiology', count: 8, icon: '❤️' },
  { name: 'Dermatology', count: 12, icon: '🧴' },
  { name: 'Orthopedics', count: 15, icon: '🦴' },
  { name: 'General Medicine', count: 25, icon: '🩺' },
  { name: 'Pediatrics', count: 10, icon: '👶' },
  { name: 'Gastroenterology', count: 9, icon: '🍽️' },
  { name: 'Neurology', count: 7, icon: '🧠' },
  { name: 'Endocrinology', count: 6, icon: '🩸' },
  { name: 'Spine & Pain Specialist', count: 5, icon: '💢' },
  { name: 'Allergy & Immunology', count: 4, icon: '🌿' },
];

export const diseases = [
  'Chest Pain',
  'Skin Rash',
  'Joint Pain',
  'Fever',
  'Headache',
  'Stomach Pain',
  'Back Pain',
  'Allergies',
  'Diabetes',
  'Hypertension',
  'Other',
];
